name: Deploy PR

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  preview_website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn    

      - name: Install website dependencies
        working-directory: website
        run: npm i

      - name: Build & export website
        working-directory: website
        run: npm run build && npm run export

      - name: Deploy website in preview mode
        working-directory: website
        run: npx netlify deploy --dir=out
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}