name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  website:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --immutable

      - name: Deploy website
        uses: ./.github/actions/deploy-website
        with:
          production: true
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
