name: docs

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  generate_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Generate API documentation
        run: npm run docs:api
