name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  verify:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['12', '14']
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint
        
      - name: Type check
        run: yarn tsc
        
      - name: Run tests
        run: yarn test

